language: minimal

jobs:
  include:
    - name: 'Classic'
      install:
        - export GAME_VERSION="classic"

    - name: 'TBC'
      install:
        - export GAME_VERSION="bcc"

addons:
  apt:
    packages:
      - luarocks

install: luarocks install --local luacheck

before_script:
  - /home/travis/.luarocks/bin/luacheck . --no-color -q

script:
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g $GAME_VERSION

notifications:
  email:
    on_success: never
    on_failure: always
